#!/bin/bash

#gcc -Wall -I/usr/local/include -c "" -lgsl -lgslcblas -lm
gcc -L/usr/local/lib -o "./bin/main" "./src/main.c" -lgsl -lgslcblas -lm -g
#gcc -Wall -o ./bin/main ./src/main.c -lm
#xmessage "Done with code $?"
zenity --info --text "Done with code $?"
